# Generated by Django 6.0.4 on 2026-05-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('N', 'Permit N — Asylum seeker'), ('F', 'Permit F — Provisional admission'), ('S', 'Permit S — Protection status'), ('B', 'Permit B — Residence permit'), ('C', 'Permit C — Settlement permit'), ('L', 'Permit L — Short-term permit'), ('G', 'Permit G — Cross-border commuter'), ('other', 'Other')], default='other', max_length=5),
        ),
    ]
