# Generated by Django 6.0.4 on 2026-05-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0004_rename_emoji_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch'), ('it', 'Italiano'), ('es', 'Español'), ('pt', 'Português'), ('ru', 'Русский')], max_length=5),
        ),
    ]
