# Generated by Django 6.0.4 on 2026-05-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0006_tag_resource_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='recommended_for_children',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='recommended_statuses',
            field=models.CharField(blank=True, help_text='Comma-separated permit codes, e.g. N,F,S', max_length=50),
        ),
    ]
