# Generated by Django 6.0.4 on 2026-05-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0007_category_recommended_for_children_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='recommended_for_children',
        ),
        migrations.RemoveField(
            model_name='category',
            name='recommended_statuses',
        ),
        migrations.AddField(
            model_name='profile',
            name='arrived_over_year_ago',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='origin_sector',
            field=models.CharField(blank=True, choices=[('healthcare', 'Healthcare'), ('education', 'Education'), ('engineering', 'Engineering & Technical'), ('trade', 'Trade & Commerce'), ('agriculture', 'Agriculture'), ('construction', 'Construction'), ('it', 'IT & Technology'), ('arts', 'Arts & Culture'), ('administration', 'Administration'), ('catering', 'Catering & Food Service'), ('transport', 'Transport & Logistics'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='other_languages',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
