# Generated by Django 6.0.4 on 2026-05-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0009_category_recommended_for_children_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='recommended_for_children',
        ),
        migrations.RemoveField(
            model_name='category',
            name='recommended_sectors',
        ),
        migrations.RemoveField(
            model_name='category',
            name='recommended_statuses',
        ),
    ]
