# Generated by Django 6.0.4 on 2026-05-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0010_remove_category_recommended_for_children_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('statuses', models.CharField(blank=True, help_text='Comma-separated permit codes, e.g. N,F,S. Empty = any.', max_length=50)),
                ('has_children', models.BooleanField(blank=True, help_text='True/False to filter, leave blank for any.', null=True)),
                ('origin_sectors', models.CharField(blank=True, help_text='Comma-separated sectors, e.g. healthcare,education. Empty = any.', max_length=200)),
                ('arrived_over_year', models.BooleanField(blank=True, help_text='True/False to filter, leave blank for any.', null=True)),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher = shown first when relevance is equal.'),
        ),
        migrations.AddField(
            model_name='category',
            name='audiences',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to show to everyone.', related_name='categories', to='pin_prototype.audience'),
        ),
    ]
