# Generated by Django 6.0.4 on 2026-05-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0011_audience_category_priority_category_audiences'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='relevant_tags',
            field=models.ManyToManyField(blank=True, help_text='Resources with these tags are shown first when this audience matches.', related_name='audiences', to='pin_prototype.tag'),
        ),
    ]
