# Generated by Django 6.0.4 on 2026-05-15 08:27

import json
from django.db import migrations, models


def convert_other_languages(apps, schema_editor):
    Profile = apps.get_model('pin_prototype', 'Profile')
    for profile in Profile.objects.all():
        raw = profile.other_languages or ''
        if not raw or raw == '[]':
            profile.other_languages = '[]'
        else:
            try:
                json.loads(raw)
                # Already valid JSON — leave as-is
            except (ValueError, TypeError):
                # Convert comma-separated string to JSON array
                langs = [l.strip() for l in raw.split(',') if l.strip()]
                profile.other_languages = json.dumps(langs)
        profile.save(update_fields=['other_languages'])


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0012_audience_relevant_tags'),
    ]

    operations = [
        migrations.RunPython(convert_other_languages, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='profile',
            name='other_languages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
