# Generated by Django 6.0.4 on 2026-05-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0013_alter_profile_other_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(choices=[('HomeIcon', 'Housing'), ('BriefcaseIcon', 'Work'), ('AcademicCapIcon', 'Education & Training'), ('HeartIcon', 'Health'), ('DocumentTextIcon', 'Documents'), ('CurrencyDollarIcon', 'Money & Benefits'), ('UsersIcon', 'Family'), ('ChatBubbleLeftIcon', 'Language'), ('ScaleIcon', 'Rights & Duties'), ('HandRaisedIcon', 'Help & Support'), ('MapPinIcon', 'Transport & Mobility'), ('ShieldCheckIcon', 'Safety'), ('StarIcon', 'Other')], default='StarIcon', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Lower = shown first.')),
                ('tags', models.ManyToManyField(blank=True, related_name='interests', to='pin_prototype.tag')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='pin_prototype.interest'),
        ),
    ]
