# Generated by Django 6.0.4 on 2026-05-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0014_interest_profile_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='group',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
