# Generated by Django 6.0.4 on 2026-05-17 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0015_add_interest_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_useful', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='pin_prototype.profile')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='pin_prototype.resource')),
            ],
            options={
                'unique_together': {('profile', 'resource')},
            },
        ),
    ]
