# Generated by Django 6.0.4 on 2026-05-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0016_add_resource_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='audiences',
            field=models.ManyToManyField(blank=True, related_name='resources', to='pin_prototype.audience'),
        ),
    ]
