# Generated by Django 6.0.4 on 2026-05-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0017_add_resource_audiences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
