# Generated by Django 6.0.4 on 2026-05-19 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0018_remove_profile_interests_delete_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='file',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('file', models.FileField(upload_to='resources/')),
                ('label', models.CharField(blank=True, max_length=200)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='pin_prototype.resource')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('text', 'Text paragraph'), ('heading', 'Heading')], default='text', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pin_prototype.resource')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
