# Generated by Django 6.0.4 on 2026-05-19 10:54

from django.db import migrations, models


def _default_body():
    return {'sections': []}


def sections_to_body(apps, schema_editor):
    """Convert existing Section rows into Editor.js JSON blocks on Resource.body."""
    Resource = apps.get_model('pin_prototype', 'Resource')
    Section = apps.get_model('pin_prototype', 'Section')

    for resource in Resource.objects.all():
        sections = list(Section.objects.filter(resource=resource).order_by('order', 'id'))
        if not sections:
            continue
        blocks = []
        for s in sections:
            content = (s.content or '').strip()
            if not content:
                continue
            if s.type == 'heading':
                blocks.append({'type': 'header', 'data': {'text': content, 'level': 2}})
            else:
                blocks.append({'type': 'paragraph', 'data': {'text': content}})
        resource.body = {'blocks': blocks}
        resource.save(update_fields=['body'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0019_remove_resource_file_attachment_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='body',
            field=models.JSONField(blank=True, default=_default_body, help_text='Editor.js article body (JSON)'),
        ),
        migrations.RunPython(sections_to_body, noop_reverse),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
