# Generated by Django 6.0.4 on 2026-05-27 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0021_body_to_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='pin_prototype.category')),
            ],
            options={
                'verbose_name_plural': 'subcategories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='pin_prototype.subcategory'),
        ),
    ]
