# Generated by Django 6.0.4 on 2026-05-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0022_subcategory_resource_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audience',
            name='origin_sectors',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='origin_sector',
        ),
        migrations.AddField(
            model_name='audience',
            name='has_driving_license',
            field=models.BooleanField(blank=True, help_text='If set, profile must match.', null=True),
        ),
        migrations.AddField(
            model_name='audience',
            name='min_computer_skills',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('advanced', 'Advanced')], help_text='Minimum computer skill level. Empty = any.', max_length=10),
        ),
        migrations.AddField(
            model_name='audience',
            name='min_education_level',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('vocational', 'Vocational'), ('bachelor', 'Bachelor'), ('master_plus', 'Master+')], help_text='Minimum education level. Empty = any.', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='computer_skills',
            field=models.CharField(blank=True, choices=[('none', 'No computer skills'), ('basic', 'Basic (internet, email)'), ('advanced', 'Advanced (office tools, digital)')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('primary', 'Primary school or less'), ('secondary', 'Secondary school (mandatory)'), ('vocational', 'Vocational training (CFC/AFP)'), ('bachelor', 'University (Bachelor or equivalent)'), ('master_plus', 'Master, Doctorate or higher')], default='primary', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_driving_license',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
