# Generated by Django 6.0.4 on 2026-06-03 09:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0024_pathway_alter_resource_category_pathwaystep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='body',
            field=wagtail.fields.StreamField([('richtext', 0), ('image', 1), ('embed', 2), ('columns', 5), ('callout', 7)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote', 'hr', 'image', 'embed'], 'label': 'Rich text'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 2: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Video / embed'}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Left column'}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Right column'}), 5: ('wagtail.blocks.StructBlock', [[('left', 3), ('right', 4)]], {'label': 'Two columns'}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'label': 'Callout text'}), 7: ('wagtail.blocks.StructBlock', [[('text', 6)]], {'label': 'Callout box'})}),
        ),
    ]
