# Generated by Django 6.0.4 on 2026-06-14 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0030_resource_fixed_sections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved')], default='approved', help_text='Guest-written resources start pending and must be approved by COSM before appearing in the app.', max_length=10),
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_default', models.BooleanField(default=False, help_text='The default author (COSM). Keep only one.')),
                ('editors', models.ManyToManyField(blank=True, help_text='Guest users who write on behalf of this organisation.', related_name='contributor_orgs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Organisation that wrote this resource. Defaults to COSM.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='pin_prototype.contributor'),
        ),
    ]
