# Generated by Django 6.0.4 on 2026-06-16 08:50

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0032_default_author_cosm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='Name shown on the map, e.g. "COSM Neuchâtel".', max_length=200)),
                ('address', models.CharField(blank=True, help_text='Full address. The location on the map is found automatically.', max_length=300)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('resource', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='pin_prototype.resource')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
