# Generated by Django 6.0.4 on 2026-06-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0033_resourceplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceplace',
            name='city',
            field=models.CharField(blank=True, help_text='City, shown under the name.', max_length=120),
        ),
        migrations.AddField(
            model_name='resourceplace',
            name='email',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='resourceplace',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='resourceplace',
            name='address',
            field=models.CharField(blank=True, help_text='Full address. The map location is found automatically.', max_length=300),
        ),
        migrations.AlterField(
            model_name='resourceplace',
            name='name',
            field=models.CharField(help_text='Name of the place, e.g. "COSM Neuchâtel".', max_length=200),
        ),
    ]
