# Generated by Django 6.0.4 on 2026-06-17 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0034_resourceplace_city_resourceplace_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=5)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('why_interesting', models.TextField(blank=True)),
                ('how_to', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pin_prototype.resource')),
            ],
            options={
                'unique_together': {('resource', 'language')},
            },
        ),
    ]
