# Generated by Django 6.0.4 on 2026-06-18 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0035_resourcetranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathway',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category this pathway is shown under.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathways', to='pin_prototype.category'),
        ),
    ]
