# Generated by Django 6.0.4 on 2026-06-22 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0037_rename_pathway_to_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category this guide is shown under.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guides', to='pin_prototype.category'),
        ),
        migrations.AlterField(
            model_name='guidestep',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_steps', to='pin_prototype.resource'),
        ),
    ]
