# Generated by Django 6.0.4 on 2026-06-22 08:01

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0038_alter_guide_category_alter_guidestep_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='pin_prototype.category'),
        ),
    ]
