# Generated by Django 6.0.4 on 2026-06-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0039_alter_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='audiences',
            field=models.ManyToManyField(blank=True, related_name='guides', to='pin_prototype.audience'),
        ),
        migrations.AddField(
            model_name='guide',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='guides', to='pin_prototype.tag'),
        ),
    ]
