# Generated by Django 6.0.4 on 2026-06-23 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0040_guide_audiences_guide_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audience',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='audience',
            name='min_age',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
