# Generated by Django 6.0.4 on 2026-06-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0041_remove_audience_max_age_remove_audience_min_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='other_languages',
        ),
        migrations.AddField(
            model_name='profile',
            name='french_level',
            field=models.CharField(blank=True, choices=[('none', 'No French yet'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='none', max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('uk', 'Українська'), ('ru', 'Русский')], max_length=5),
        ),
    ]
