# Generated by Django 6.0.4 on 2026-06-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0043_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='origin_sector',
            field=models.CharField(blank=True, choices=[('healthcare', 'Healthcare'), ('education', 'Education'), ('engineering', 'Engineering'), ('trade', 'Trade & commerce'), ('agriculture', 'Agriculture'), ('construction', 'Construction'), ('it', 'IT & technology'), ('arts', 'Arts & culture'), ('administration', 'Administration'), ('catering', 'Catering & food'), ('transport', 'Transport'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('vocational', 'Vocational training (CFC/AFP)'), ('bachelor', 'University (Bachelor or equivalent)'), ('master_plus', 'Master, Doctorate or higher')], default='', max_length=15),
        ),
    ]
