# Generated by Django 6.0.4 on 2026-06-26 12:35

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0044_profile_origin_sector_alter_profile_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='body',
            field=wagtail.fields.StreamField([('section', 3)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('why', 'Why is it interesting?'), ('how', 'How to do it?'), ('location', 'Location'), ('custom', 'Custom section')]}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title shown for a custom section (ignored for the three standard kinds).', 'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'bold', 'italic', 'link', 'document-link', 'ol', 'ul', 'blockquote', 'hr', 'image', 'embed']}), 3: ('wagtail.blocks.StructBlock', [[('kind', 0), ('heading', 1), ('content', 2)]], {})}, verbose_name='Body (sections)'),
        ),
        migrations.AddField(
            model_name='resourcetranslation',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='how_to',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='How to do it? (legacy)'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='location',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Location (legacy)'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='why_interesting',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Why is it interesting? (legacy)'),
        ),
    ]
