# Generated by Django 6.0.4 on 2026-06-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0046_populate_resource_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetranslation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved')], default='approved', help_text='Only approved translations appear in the app. AI translations are set to pending for review.', max_length=10),
        ),
    ]
