# Generated by Django 6.0.4 on 2026-06-26 13:19

import wagtail.fields
from django.db import migrations


def clear_translations(apps, schema_editor):
    """The old `body` stored a plain-JSON list, incompatible with the new
    StreamField format. Drop existing (placeholder) translations; they are
    regenerated by the seed or `translate_resources`."""
    apps.get_model('pin_prototype', 'ResourceTranslation').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0047_resourcetranslation_status'),
    ]

    operations = [
        migrations.RunPython(clear_translations, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='resourcetranslation',
            name='how_to',
        ),
        migrations.RemoveField(
            model_name='resourcetranslation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='resourcetranslation',
            name='why_interesting',
        ),
        migrations.AlterField(
            model_name='resourcetranslation',
            name='body',
            field=wagtail.fields.StreamField([('section', 3)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('why', 'Why is it interesting?'), ('how', 'How to do it?'), ('location', 'Location'), ('custom', 'Custom section')]}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title shown for a custom section (ignored for the three standard kinds).', 'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'bold', 'italic', 'link', 'document-link', 'ol', 'ul', 'blockquote', 'hr', 'image', 'embed']}), 3: ('wagtail.blocks.StructBlock', [[('kind', 0), ('heading', 1), ('content', 2)]], {})}, verbose_name='Body (sections)'),
        ),
    ]
