# Generated by Django 6.0.4 on 2026-06-26 14:18

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


def copy_order_to_sort_order(apps, schema_editor):
    GuideStep = apps.get_model('pin_prototype', 'GuideStep')
    for step in GuideStep.objects.all():
        step.sort_order = step.order
        step.save(update_fields=['sort_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0048_remove_resourcetranslation_how_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guidestep',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='guidestep',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        # Preserve the existing step order before dropping the old field.
        migrations.RunPython(copy_order_to_sort_order, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='guidestep',
            name='order',
        ),
        migrations.AlterField(
            model_name='guidestep',
            name='guide',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pin_prototype.guide'),
        ),
        migrations.AlterField(
            model_name='guidestep',
            name='step_label',
            field=models.CharField(blank=True, help_text='Optional step title. Defaults to the resource name.', max_length=200),
        ),
    ]
