# Generated by Django 6.0.4 on 2026-06-29 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0049_alter_guidestep_options_remove_guidestep_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=5)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved')], default='approved', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pin_prototype.guide')),
            ],
            options={
                'unique_together': {('guide', 'language')},
            },
        ),
    ]
