# Generated by Django 6.0.4 on 2026-07-02 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0050_guidetranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='audiences',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='audiences',
        ),
    ]
