# Generated by Django 6.0.4 on 2026-07-04 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin_prototype', '0051_remove_guide_audiences_remove_resource_audiences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='how_to',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='location',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='why_interesting',
        ),
    ]
